httpbin:
  image:
    repository: kennethreitz/httpbin
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 512Mi
  replicas: 1
  service:
    type: ClusterIP
    port: 80

hpa:
  minReplicas: 6
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50

pdb:
  minAvailable: 50%

stressTest:
  schedule: "00 12 * * 1,4" # At 12:00 on Monday and Thursday.
  image:
    repository: ricoli/hey
    tag: latest
    pullPolicy: IfNotPresent
  args:
    - "-z"
    - "5m"
    - "-c"
    - "200"
    - "http://httpbin-service/bytes/4096"

