apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  labels:
    app: httpbin
spec:
  type: {{ .Values.httpbin.service.type }}
  ports:
    - port: {{ .Values.httpbin.service.port }}
      targetPort: {{ .Values.httpbin.service.port }}
  selector:
    app: httpbin