apiVersion: batch/v1
kind: CronJob
metadata:
  name: stress-test
  labels:
    app: stress-test
spec:
  schedule: "{{ .Values.stressTest.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: stress-test
              image: "{{ .Values.stressTest.image.repository }}:{{ .Values.stressTest.image.tag }}"
              imagePullPolicy: {{ .Values.stressTest.image.pullPolicy }}
              args: 
                {{- toYaml .Values.stressTest.args | nindent 16 }}
          restartPolicy: Never
      backoffLimit: 4